language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
# command to install dependencies
install:
 - pip install Django==$DJANGO_VERSION
 - pip install -r dev_requirements.txt
# command to run tests
script:
 - python setup.py test
