language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
# command to install dependencies
install:
 - pip install -r requirements.txt
# command to run tests
env:
  # - DJANGO=1.2.7
  # - DJANGO=1.3.1
  - DJANGO=1.4.3 DJANGO_SETTINGS_MODULE="postjust.settings_prod"
script: python manage.py test
