language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
# command to install dependencies
install:
 - pip install Django==$DJANGO_VERSION
 - pip install -r requirements.txt
# command to run tests
env:
  - DJANGO_VERSION=1.2.7 DJANGO_SETTINGS_MODULE="postjust.settings"
  - DJANGO_VERSION=1.3.1 DJANGO_SETTINGS_MODULE="postjust.settings"
script: nosetests
